// SPDX-License-Identifier: GPL-3.0-or-later
package dropcrypto

import (
	"bytes"
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"testing"
)

type vectorFile struct {
	V       int      `json:"v"`
	Vectors []vector `json:"vectors"`
}

type vector struct {
	Name   string `json:"name"`
	PlanID string `json:"planId"`
	Key    string `json:"key"`
	IV     string `json:"iv"`
	Plain  string `json:"plain"`
	CT     string `json:"ct"`
	Gzip   bool   `json:"gzip,omitempty"`
}

// det mirrors runner/genvectors.mjs: deterministic bytes via sha256 counter.
func det(label string, n int) []byte {
	out := make([]byte, 0, n)
	for counter := 0; len(out) < n; counter++ {
		block := sha256.Sum256([]byte(fmt.Sprintf("%s:%d", label, counter)))
		out = append(out, block[:]...)
	}
	return out[:n]
}

func mustB64(t *testing.T, s string) []byte {
	t.Helper()
	b, err := B64urlDecode(s)
	if err != nil {
		t.Fatalf("b64url decode: %v", err)
	}
	return b
}

// TestNodeVectors: the Node->Go leg. Requires testdata/vectors.json,
// generated by `node runner/genvectors.mjs internal/dropcrypto/testdata/vectors.json`.
func TestNodeVectors(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join("testdata", "vectors.json"))
	if err != nil {
		t.Skipf("no vectors.json — run: node runner/genvectors.mjs internal/dropcrypto/testdata/vectors.json (%v)", err)
	}
	var vf vectorFile
	if err := json.Unmarshal(raw, &vf); err != nil {
		t.Fatalf("parse vectors: %v", err)
	}
	if len(vf.Vectors) < 4 {
		t.Fatalf("suspiciously few vectors: %d", len(vf.Vectors))
	}
	for _, v := range vf.Vectors {
		t.Run(v.Name, func(t *testing.T) {
			key := mustB64(t, v.Key)
			iv := mustB64(t, v.IV)
			plain := mustB64(t, v.Plain)
			ct := mustB64(t, v.CT)

			got, err := Decrypt(key, v.PlanID, iv, ct)
			if err != nil {
				t.Fatalf("decrypt node ct: %v", err)
			}
			if !bytes.Equal(got, plain) {
				t.Fatalf("plaintext mismatch")
			}
			// AES-GCM is deterministic under a fixed IV: Go encrypt must be
			// byte-identical with Node's ciphertext.
			goCT, err := EncryptWithIV(key, v.PlanID, iv, plain)
			if err != nil {
				t.Fatalf("encrypt: %v", err)
			}
			if !bytes.Equal(goCT, ct) {
				t.Fatalf("ciphertext mismatch (Go encrypt != Node encrypt)")
			}
			// AAD binding: a different planId must fail
			if _, err := Decrypt(key, v.PlanID+"x", iv, ct); err == nil {
				t.Fatalf("AAD mismatch did not fail")
			}
			// tamper must fail
			bad := append([]byte(nil), ct...)
			bad[0] ^= 1
			if _, err := Decrypt(key, v.PlanID, iv, bad); err == nil {
				t.Fatalf("tampered ct did not fail")
			}
		})
	}
}

// TestWriteGoVectors: the Go->Node leg. Writes testdata/govectors.json for
// `node runner/checkvectors.mjs` (run in CI after this test).
func TestWriteGoVectors(t *testing.T) {
	if err := os.MkdirAll("testdata", 0o755); err != nil {
		t.Fatal(err)
	}
	var out vectorFile
	out.V = 1
	cases := []struct {
		name   string
		planID string
		plain  []byte
		gz     bool
	}{
		{"go-short", "AbC123xy", []byte("go says hello"), false},
		{"go-empty", "AbC123xy", nil, false},
		{"go-gzip", "AbC123xy", nil, true},
		{"go-big", "Zz9_-Pl0", det("go-big-plain", 64*1024), false},
	}
	for _, c := range cases {
		plain := c.plain
		if c.gz {
			var err error
			plain, err = Gzip([]byte(`[1,"AbC123xy","Go-Plan",1755600000,0,[],[],[],0,[]]`))
			if err != nil {
				t.Fatal(err)
			}
		}
		key := det("gokey:"+c.name, 32)
		iv := det("goiv:"+c.name, 12)
		ct, err := EncryptWithIV(key, c.planID, iv, plain)
		if err != nil {
			t.Fatal(err)
		}
		out.Vectors = append(out.Vectors, vector{
			Name:   c.name,
			PlanID: c.planID,
			Key:    B64urlEncode(key),
			IV:     B64urlEncode(iv),
			Plain:  B64urlEncode(plain),
			CT:     B64urlEncode(ct),
			Gzip:   c.gz,
		})
	}
	data, err := json.MarshalIndent(out, "", " ")
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join("testdata", "govectors.json"), data, 0o644); err != nil {
		t.Fatal(err)
	}
}

func TestStateFileRoundtrip(t *testing.T) {
	key := det("sfkey", 32)
	iv, ct, err := Encrypt(key, "PlanXYZ1", []byte("state"))
	if err != nil {
		t.Fatal(err)
	}
	text, err := SerializeStateFile(7, "2026-08-20T12:00:00.000Z", iv, ct)
	if err != nil {
		t.Fatal(err)
	}
	rev, at, iv2, ct2, err := ParseStateFile(text)
	if err != nil {
		t.Fatal(err)
	}
	if rev != 7 || at != "2026-08-20T12:00:00.000Z" || !bytes.Equal(iv, iv2) || !bytes.Equal(ct, ct2) {
		t.Fatalf("roundtrip mismatch")
	}
	plain, err := Decrypt(key, "PlanXYZ1", iv2, ct2)
	if err != nil || string(plain) != "state" {
		t.Fatalf("decrypt after roundtrip: %v %q", err, plain)
	}
	if _, _, _, _, err := ParseStateFile([]byte(`{"v":2}`)); err == nil {
		t.Fatalf("bad shape accepted")
	}
}

func TestFreshIV(t *testing.T) {
	key := det("ivkey", 32)
	iv1, _, err := Encrypt(key, "p", []byte("x"))
	if err != nil {
		t.Fatal(err)
	}
	iv2, _, err := Encrypt(key, "p", []byte("x"))
	if err != nil {
		t.Fatal(err)
	}
	if bytes.Equal(iv1, iv2) {
		t.Fatalf("IV reuse")
	}
}

func TestGzipRoundtripAndCap(t *testing.T) {
	data := det("gz", 10000)
	gz, err := Gzip(data)
	if err != nil {
		t.Fatal(err)
	}
	back, err := Gunzip(gz)
	if err != nil || !bytes.Equal(back, data) {
		t.Fatalf("gzip roundtrip: %v", err)
	}
	// a bomb over the cap must be rejected
	bomb, err := Gzip(make([]byte, MaxGunzipBytes+10))
	if err != nil {
		t.Fatal(err)
	}
	if _, err := Gunzip(bomb); err == nil {
		t.Fatalf("gunzip cap not enforced")
	}
}
